
language: python

python:
    - 2.7.8
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - pypy3

install:
    - export PYTHONPATH=$PYTHONPATH:../source/
script:
    - cd llt
    - py.test

